import { sql } from "kysely";
import type { Kysely } from "kysely";

// Frozen baseline under DEC-20260912-010. Future policy changes use a new migration.
export async function up(db: Kysely<unknown>): Promise<void> {
  for (const statement of statements) await sql.raw(statement).execute(db);
}

export async function down(db: Kysely<unknown>): Promise<void> {
  await sql`DROP TABLE app.automation_run`.execute(db);
  await sql`DROP TABLE app.automation_job`.execute(db);
  await sql`DROP TABLE app.thumbnail_review`.execute(db);
  await sql`DROP TABLE app.thumbnail_job`.execute(db);
  await sql`DROP TABLE app.thumbnail_recipe`.execute(db);
  await sql`DROP TABLE app.identifier_candidate`.execute(db);
  await sql`DROP TABLE app.identifier_resolve_run`.execute(db);
  await sql`DROP TABLE app.import_item`.execute(db);
  await sql`DROP TABLE app.import_batch`.execute(db);
  await sql`DROP TABLE app.product_image`.execute(db);
  await sql`DROP TABLE app.source_sku`.execute(db);
  await sql`DROP TABLE app.source_product`.execute(db);
  await sql`DROP TABLE app.product_identifier`.execute(db);
  await sql`DROP TABLE app.product_sku`.execute(db);
  await sql`DROP TABLE app.product_master`.execute(db);
  await sql`DROP TABLE app.brand_alias`.execute(db);
  await sql`DROP TABLE app.brand`.execute(db);
  await sql`DROP TABLE app.platform`.execute(db);
  await sql`DROP FUNCTION app.validate_automation_timezone()`.execute(db);
  await sql`DROP SCHEMA app`.execute(db);
  // pg_trgm and migration history may be shared; never cascade-drop either.
}

const statements = [
  `CREATE SCHEMA IF NOT EXISTS app`,
  `CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public`,
  `CREATE TABLE app.platform (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  code varchar(100) NOT NULL CHECK (code ~ '[^[:space:]]'),
  name text NOT NULL CHECK (name ~ '[^[:space:]]'),
  platform_role varchar(64) NOT NULL CHECK (platform_role IN ('SOURCE', 'CHANNEL', 'INTEGRATION')),
  is_active boolean NOT NULL DEFAULT true,
  config_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(config_json) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (code)
)`,
  `CREATE TABLE app.brand (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  brand_key varchar(100) NOT NULL CHECK (brand_key ~ '[^[:space:]]'),
  name_ko text,
  name_en text,
  official_url text,
  is_active boolean NOT NULL DEFAULT true,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata_json) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (brand_key),
  CHECK (COALESCE(name_ko, '') ~ '[^[:space:]]' OR COALESCE(name_en, '') ~ '[^[:space:]]')
)`,
  `CREATE TABLE app.brand_alias (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  brand_id bigint NOT NULL REFERENCES app.brand(id) ON DELETE RESTRICT,
  platform_id bigint REFERENCES app.platform(id) ON DELETE RESTRICT,
  alias_name text NOT NULL CHECK (alias_name ~ '[^[:space:]]'),
  alias_norm text NOT NULL CHECK (alias_norm ~ '[^[:space:]]'),
  created_at timestamptz NOT NULL DEFAULT now()
)`,
  `CREATE INDEX brand_alias_brand_id_idx ON app.brand_alias (brand_id)`,
  `CREATE INDEX brand_alias_platform_id_idx ON app.brand_alias (platform_id)`,
  `CREATE TABLE app.product_master (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  brand_id bigint REFERENCES app.brand(id) ON DELETE RESTRICT,
  product_name text NOT NULL CHECK (product_name ~ '[^[:space:]]'),
  product_name_norm text NOT NULL CHECK (product_name_norm ~ '[^[:space:]]'),
  category_key varchar(64) NOT NULL DEFAULT 'UNKNOWN' CHECK (category_key ~ '[^[:space:]]'),
  product_type varchar(64) NOT NULL DEFAULT 'UNKNOWN' CHECK (product_type ~ '[^[:space:]]'),
  status varchar(64) NOT NULL DEFAULT 'REVIEW_REQUIRED' CHECK (status IN ('ACTIVE', 'INACTIVE', 'REVIEW_REQUIRED')),
  identifier_status varchar(64) NOT NULL DEFAULT 'UNKNOWN' CHECK (identifier_status IN ('UNKNOWN', 'SEARCHING', 'CANDIDATE', 'REVIEW_REQUIRED', 'VERIFIED', 'NOT_FOUND', 'NOT_APPLICABLE')),
  created_method varchar(64) NOT NULL CHECK (created_method ~ '[^[:space:]]'),
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata_json) = 'object'),
  version_no integer NOT NULL DEFAULT 1 CHECK (version_no >= 1),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
)`,
  `CREATE INDEX product_master_brand_id_idx ON app.product_master (brand_id)`,
  `CREATE TABLE app.product_sku (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  product_id bigint NOT NULL REFERENCES app.product_master(id) ON DELETE RESTRICT,
  sku_name text NOT NULL CHECK (sku_name ~ '[^[:space:]]'),
  option_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(option_json) = 'object'),
  option_key text NOT NULL CHECK (option_key ~ '[^[:space:]]'),
  status varchar(64) NOT NULL DEFAULT 'REVIEW_REQUIRED' CHECK (status IN ('ACTIVE', 'INACTIVE', 'REVIEW_REQUIRED')),
  sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (product_id, option_key),
  UNIQUE (id, product_id)
)`,
  `CREATE INDEX product_sku_product_id_idx ON app.product_sku (product_id)`,
  `CREATE TABLE app.product_identifier (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  product_id bigint NOT NULL REFERENCES app.product_master(id) ON DELETE RESTRICT,
  sku_id bigint REFERENCES app.product_sku(id) ON DELETE RESTRICT,
  identifier_type varchar(64) NOT NULL CHECK (identifier_type IN ('MODEL_NO', 'STYLE_CODE', 'PRODUCT_NO', 'MPN', 'GTIN', 'EAN', 'UPC', 'BARCODE', 'BRAND_CODE')),
  identifier_value text NOT NULL CHECK (identifier_value ~ '[^[:space:]]'),
  identifier_norm text NOT NULL CHECK (identifier_norm ~ '[^[:space:]]'),
  is_primary boolean NOT NULL DEFAULT false,
  is_verified boolean NOT NULL DEFAULT false,
  confidence_score numeric(5,2) CHECK (confidence_score BETWEEN 0 AND 100),
  evidence_type varchar(64) NOT NULL CHECK (evidence_type ~ '[^[:space:]]'),
  source_url text,
  evidence_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(evidence_json) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (sku_id, product_id) REFERENCES app.product_sku(id, product_id) ON DELETE RESTRICT
)`,
  `CREATE INDEX product_identifier_product_id_idx ON app.product_identifier (product_id)`,
  `CREATE INDEX product_identifier_sku_id_idx ON app.product_identifier (sku_id)`,
  `CREATE TABLE app.source_product (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  platform_id bigint NOT NULL REFERENCES app.platform(id) ON DELETE RESTRICT,
  external_product_id text NOT NULL CHECK (external_product_id ~ '[^[:space:]]'),
  product_id bigint REFERENCES app.product_master(id) ON DELETE RESTRICT,
  product_url text,
  raw_product_name text NOT NULL CHECK (raw_product_name ~ '[^[:space:]]'),
  raw_brand_name text,
  current_price numeric(20,4) CHECK (current_price >= 0 AND current_price <> 'NaN'::numeric),
  normal_price numeric(20,4) CHECK (normal_price >= 0 AND normal_price <> 'NaN'::numeric),
  currency_code varchar(3) CHECK (currency_code ~ '^[A-Z]{3}$'),
  stock_status varchar(64) NOT NULL DEFAULT 'UNKNOWN' CHECK (stock_status IN ('UNKNOWN', 'IN_STOCK', 'OUT_OF_STOCK')),
  match_status varchar(64) NOT NULL DEFAULT 'UNMATCHED' CHECK (match_status IN ('UNMATCHED', 'MATCHED', 'REVIEW_REQUIRED')),
  match_confidence numeric(5,2) CHECK (match_confidence BETWEEN 0 AND 100),
  raw_json jsonb NOT NULL,
  collected_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (platform_id, external_product_id)
)`,
  `CREATE INDEX source_product_platform_id_idx ON app.source_product (platform_id)`,
  `CREATE INDEX source_product_product_id_idx ON app.source_product (product_id)`,
  `CREATE TABLE app.source_sku (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  source_product_id bigint NOT NULL REFERENCES app.source_product(id) ON DELETE RESTRICT,
  sku_id bigint REFERENCES app.product_sku(id) ON DELETE RESTRICT,
  external_sku_id text,
  raw_option_name text NOT NULL CHECK (raw_option_name ~ '[^[:space:]]'),
  option_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(option_json) = 'object'),
  option_key text NOT NULL CHECK (option_key ~ '[^[:space:]]'),
  current_price numeric(20,4) CHECK (current_price >= 0 AND current_price <> 'NaN'::numeric),
  stock_status varchar(64) NOT NULL DEFAULT 'UNKNOWN' CHECK (stock_status IN ('UNKNOWN', 'IN_STOCK', 'OUT_OF_STOCK')),
  raw_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_product_id, option_key)
)`,
  `CREATE INDEX source_sku_source_product_id_idx ON app.source_sku (source_product_id)`,
  `CREATE INDEX source_sku_sku_id_idx ON app.source_sku (sku_id)`,
  `CREATE TABLE app.product_image (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  product_id bigint REFERENCES app.product_master(id) ON DELETE RESTRICT,
  sku_id bigint REFERENCES app.product_sku(id) ON DELETE RESTRICT,
  source_product_id bigint REFERENCES app.source_product(id) ON DELETE RESTRICT,
  image_type varchar(64) NOT NULL CHECK (image_type IN ('SOURCE_MAIN', 'SOURCE_DETAIL', 'GENERATED_THUMBNAIL', 'CHANNEL_MAIN', 'CHANNEL_DETAIL')),
  source_image_id bigint REFERENCES app.product_image(id) ON DELETE RESTRICT,
  source_url text,
  storage_provider text,
  storage_bucket text,
  object_key text,
  mime_type text,
  width integer CHECK (width > 0),
  height integer CHECK (height > 0),
  file_size bigint CHECK (file_size > 0),
  content_hash char(64) CHECK (content_hash ~ '^[0-9a-f]{64}$'),
  recipe_hash char(64) CHECK (recipe_hash ~ '^[0-9a-f]{64}$'),
  process_status varchar(64) NOT NULL DEFAULT 'REGISTERED' CHECK (process_status IN ('REGISTERED', 'FETCHING', 'STORED', 'FAILED')),
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata_json) = 'object'),
  source_revision integer NOT NULL DEFAULT 1 CHECK (source_revision >= 1),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (product_id IS NOT NULL OR source_product_id IS NOT NULL),
  CHECK (sku_id IS NULL OR product_id IS NOT NULL),
  FOREIGN KEY (sku_id, product_id) REFERENCES app.product_sku(id, product_id) ON DELETE RESTRICT,
  CHECK (num_nonnulls(storage_provider, storage_bucket, object_key, content_hash, mime_type, width, height, file_size) IN (0, 8)),
  CHECK (process_status <> 'STORED' OR num_nonnulls(storage_provider, storage_bucket, object_key, content_hash, mime_type, width, height, file_size) = 8),
  CHECK (image_type <> 'GENERATED_THUMBNAIL' OR (source_image_id IS NOT NULL AND recipe_hash IS NOT NULL AND num_nonnulls(storage_provider, storage_bucket, object_key, content_hash, mime_type, width, height, file_size) = 8))
)`,
  `CREATE INDEX product_image_product_id_idx ON app.product_image (product_id)`,
  `CREATE INDEX product_image_sku_id_idx ON app.product_image (sku_id)`,
  `CREATE INDEX product_image_source_product_id_idx ON app.product_image (source_product_id)`,
  `CREATE INDEX product_image_source_image_id_idx ON app.product_image (source_image_id)`,
  `CREATE TABLE app.import_batch (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  platform_id bigint NOT NULL REFERENCES app.platform(id) ON DELETE RESTRICT,
  import_type varchar(64) NOT NULL CHECK (import_type ~ '[^[:space:]]'),
  status varchar(64) NOT NULL DEFAULT 'QUEUED' CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL_FAILED', 'FAILED', 'CANCELLED')),
  total_count integer NOT NULL DEFAULT 0 CHECK (total_count >= 0),
  success_count integer NOT NULL DEFAULT 0 CHECK (success_count >= 0),
  failed_count integer NOT NULL DEFAULT 0 CHECK (failed_count >= 0),
  skipped_count integer NOT NULL DEFAULT 0 CHECK (skipped_count >= 0),
  review_count integer NOT NULL DEFAULT 0 CHECK (review_count >= 0),
  source_name text NOT NULL CHECK (source_name ~ '[^[:space:]]'),
  config_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(config_json) = 'object'),
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (started_at <= finished_at),
  CHECK (status NOT IN ('SUCCEEDED', 'PARTIAL_FAILED', 'FAILED', 'CANCELLED') OR total_count::bigint = success_count::bigint + failed_count::bigint + skipped_count::bigint + review_count::bigint),
  CHECK (status <> 'SUCCEEDED' OR failed_count = 0),
  CHECK (status <> 'PARTIAL_FAILED' OR (failed_count > 0 AND failed_count < total_count)),
  CHECK (status <> 'FAILED' OR failed_count = total_count)
)`,
  `CREATE INDEX import_batch_platform_id_idx ON app.import_batch (platform_id)`,
  `CREATE TABLE app.import_item (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  import_batch_id bigint NOT NULL REFERENCES app.import_batch(id) ON DELETE RESTRICT,
  external_product_id text,
  source_product_id bigint REFERENCES app.source_product(id) ON DELETE RESTRICT,
  status varchar(64) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'REVIEW_REQUIRED', 'SKIPPED', 'FAILED')),
  action_type varchar(64) CHECK (action_type IN ('CREATED', 'UPDATED', 'MATCHED', 'REVIEW_REQUIRED', 'SKIPPED', 'FAILED')),
  error_code varchar(64),
  error_message text,
  raw_json jsonb NOT NULL,
  processed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  input_row_no integer NOT NULL CHECK (input_row_no >= 1),
  UNIQUE (import_batch_id, input_row_no)
)`,
  `CREATE INDEX import_item_import_batch_id_idx ON app.import_item (import_batch_id)`,
  `CREATE INDEX import_item_source_product_id_idx ON app.import_item (source_product_id)`,
  `CREATE TABLE app.identifier_resolve_run (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  source_product_id bigint NOT NULL REFERENCES app.source_product(id) ON DELETE RESTRICT,
  product_id bigint REFERENCES app.product_master(id) ON DELETE RESTRICT,
  resolver_version text NOT NULL CHECK (resolver_version ~ '[^[:space:]]'),
  status varchar(64) NOT NULL DEFAULT 'QUEUED' CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
  input_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(input_json) = 'object'),
  error_code varchar(64),
  error_message text,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (started_at <= finished_at)
)`,
  `CREATE INDEX identifier_resolve_run_source_product_id_idx ON app.identifier_resolve_run (source_product_id)`,
  `CREATE INDEX identifier_resolve_run_product_id_idx ON app.identifier_resolve_run (product_id)`,
  `CREATE TABLE app.identifier_candidate (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  resolve_run_id bigint NOT NULL REFERENCES app.identifier_resolve_run(id) ON DELETE RESTRICT,
  identifier_type varchar(64) NOT NULL CHECK (identifier_type IN ('MODEL_NO', 'STYLE_CODE', 'PRODUCT_NO', 'MPN', 'GTIN', 'EAN', 'UPC', 'BARCODE', 'BRAND_CODE')),
  candidate_value text NOT NULL CHECK (candidate_value ~ '[^[:space:]]'),
  candidate_norm text NOT NULL CHECK (candidate_norm ~ '[^[:space:]]'),
  confidence_score numeric(5,2) CHECK (confidence_score BETWEEN 0 AND 100),
  rank_no integer NOT NULL CHECK (rank_no >= 1),
  decision_status varchar(64) NOT NULL DEFAULT 'CANDIDATE' CHECK (decision_status IN ('CANDIDATE', 'AUTO_ACCEPTED', 'REVIEW_REQUIRED', 'ACCEPTED', 'REJECTED')),
  evidence_json jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(evidence_json) = 'array'),
  conflict_json jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(conflict_json) = 'array'),
  created_at timestamptz NOT NULL DEFAULT now(),
  version_no integer NOT NULL DEFAULT 1 CHECK (version_no >= 1),
  decided_at timestamptz,
  decided_by text,
  UNIQUE (resolve_run_id, identifier_type, candidate_norm)
)`,
  `CREATE INDEX identifier_candidate_resolve_run_id_idx ON app.identifier_candidate (resolve_run_id)`,
  `CREATE TABLE app.thumbnail_recipe (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  recipe_code varchar(100) NOT NULL CHECK (recipe_code ~ '[^[:space:]]'),
  recipe_name text NOT NULL CHECK (recipe_name ~ '[^[:space:]]'),
  version_no integer NOT NULL DEFAULT 1 CHECK (version_no >= 1),
  output_width integer NOT NULL DEFAULT 1000 CHECK (output_width >= 1),
  output_height integer NOT NULL DEFAULT 1000 CHECK (output_height >= 1),
  policy_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(policy_json) = 'object'),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (recipe_code, version_no)
)`,
  `CREATE TABLE app.thumbnail_job (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  product_image_id bigint NOT NULL REFERENCES app.product_image(id) ON DELETE RESTRICT,
  recipe_id bigint NOT NULL REFERENCES app.thumbnail_recipe(id) ON DELETE RESTRICT,
  status varchar(64) NOT NULL DEFAULT 'QUEUED' CHECK (status IN ('QUEUED', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
  path_type varchar(64) CHECK (path_type IN ('SAFE_COMPOSITE', 'AI_EDIT', 'AI_RECONSTRUCT')),
  attempt_no integer NOT NULL DEFAULT 0 CHECK (attempt_no >= 0),
  error_code varchar(64),
  error_message text,
  input_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(input_json) = 'object'),
  analysis_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(analysis_json) = 'object'),
  result_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(result_json) = 'object'),
  queued_at timestamptz,
  started_at timestamptz,
  finished_at timestamptz,
  request_key text NOT NULL CHECK (request_key ~ '[^[:space:]]'),
  recipe_hash char(64) CHECK (recipe_hash ~ '^[0-9a-f]{64}$'),
  provider_key text,
  model_version text,
  processing_version text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (request_key),
  CHECK (started_at <= finished_at),
  CHECK (status <> 'SUCCEEDED' OR (recipe_hash IS NOT NULL AND processing_version IS NOT NULL AND processing_version ~ '[^[:space:]]'))
)`,
  `CREATE INDEX thumbnail_job_product_image_id_idx ON app.thumbnail_job (product_image_id)`,
  `CREATE INDEX thumbnail_job_recipe_id_idx ON app.thumbnail_job (recipe_id)`,
  `CREATE TABLE app.thumbnail_review (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  thumbnail_job_id bigint NOT NULL REFERENCES app.thumbnail_job(id) ON DELETE RESTRICT,
  review_status varchar(64) NOT NULL CHECK (review_status IN ('AUTO_APPROVED', 'REVIEW_REQUIRED', 'MANUAL_APPROVED', 'REJECTED', 'REGENERATE_REQUIRED')),
  issue_codes text[] NOT NULL DEFAULT '{}'::text[],
  score numeric(5,2) CHECK (score BETWEEN 0 AND 100),
  reviewer_type varchar(64) NOT NULL CHECK (reviewer_type ~ '[^[:space:]]'),
  reviewer_name text,
  reviewed_at timestamptz,
  version_no integer NOT NULL DEFAULT 1 CHECK (version_no >= 1),
  UNIQUE (thumbnail_job_id, version_no)
)`,
  `CREATE INDEX thumbnail_review_thumbnail_job_id_idx ON app.thumbnail_review (thumbnail_job_id)`,
  `CREATE TABLE app.automation_job (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  job_code varchar(100) NOT NULL CHECK (job_code ~ '[^[:space:]]'),
  job_name text NOT NULL CHECK (job_name ~ '[^[:space:]]'),
  job_type varchar(64) NOT NULL CHECK (job_type IN ('BROWSER', 'INTERNAL', 'API')),
  handler_key text NOT NULL CHECK (handler_key ~ '[^[:space:]]'),
  profile_key text,
  cron_expression text,
  timezone text NOT NULL DEFAULT 'Asia/Seoul' CHECK (timezone ~ '[^[:space:]]'),
  enabled boolean NOT NULL DEFAULT true,
  allow_manual_run boolean NOT NULL DEFAULT true,
  allow_parallel boolean NOT NULL DEFAULT false,
  max_retries integer NOT NULL DEFAULT 2 CHECK (max_retries >= 0),
  cooldown_seconds integer NOT NULL DEFAULT 60 CHECK (cooldown_seconds >= 0),
  timeout_seconds integer NOT NULL DEFAULT 300 CHECK (timeout_seconds >= 1),
  config_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(config_json) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  version_no integer NOT NULL DEFAULT 1 CHECK (version_no >= 1),
  CHECK (job_type <> 'BROWSER' OR (profile_key IS NOT NULL AND profile_key ~ '[^[:space:]]'))
)`,
  `CREATE TABLE app.automation_run (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT uuidv7() UNIQUE,
  automation_job_id bigint NOT NULL REFERENCES app.automation_job(id) ON DELETE RESTRICT,
  queue_provider varchar(30),
  queue_job_id varchar(200),
  status varchar(64) NOT NULL DEFAULT 'QUEUED' CHECK (status IN ('QUEUED', 'RUNNING', 'RETRY_WAIT', 'SUCCESS', 'FAILED', 'TIMEOUT', 'CANCELLED')),
  attempt_no integer NOT NULL DEFAULT 0 CHECK (attempt_no >= 0),
  current_step text,
  error_code varchar(64),
  error_message text,
  current_url text,
  input_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(input_json) = 'object'),
  result_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(result_json) = 'object'),
  screenshot_key text,
  trace_key text,
  queued_at timestamptz,
  started_at timestamptz,
  finished_at timestamptz,
  request_key text NOT NULL CHECK (request_key ~ '[^[:space:]]'),
  trigger_type varchar(16) NOT NULL CHECK (trigger_type IN ('MANUAL', 'SCHEDULED')),
  scheduled_for timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (request_key),
  CHECK (started_at <= finished_at),
  CHECK ((queue_provider IS NULL) = (queue_job_id IS NULL))
)`,
  `CREATE INDEX automation_run_automation_job_id_idx ON app.automation_run (automation_job_id)`,
  `CREATE UNIQUE INDEX brand_alias_scope_norm_uq ON app.brand_alias (COALESCE(platform_id, 0), alias_norm)`,
  `CREATE UNIQUE INDEX product_identifier_scope_norm_uq ON app.product_identifier (product_id, COALESCE(sku_id, 0), identifier_type, identifier_norm)`,
  `CREATE UNIQUE INDEX product_identifier_primary_uq ON app.product_identifier (product_id, COALESCE(sku_id, 0), identifier_type) WHERE is_primary`,
  `CREATE UNIQUE INDEX source_sku_external_uq ON app.source_sku (source_product_id, external_sku_id) WHERE external_sku_id IS NOT NULL`,
  `CREATE UNIQUE INDEX product_image_generated_uq ON app.product_image (source_image_id, image_type, recipe_hash) WHERE image_type = 'GENERATED_THUMBNAIL'`,
  `CREATE UNIQUE INDEX product_image_source_revision_uq ON app.product_image (source_product_id, image_type, source_url, source_revision) WHERE image_type IN ('SOURCE_MAIN', 'SOURCE_DETAIL')`,
  `CREATE INDEX product_master_brand_identifier_idx ON app.product_master (brand_id, identifier_status)`,
  `CREATE INDEX product_master_identifier_status_idx ON app.product_master (identifier_status)`,
  `CREATE INDEX product_master_name_trgm_idx ON app.product_master USING gin (product_name_norm public.gin_trgm_ops)`,
  `CREATE INDEX source_product_platform_last_seen_idx ON app.source_product (platform_id, last_seen_at)`,
  `CREATE INDEX product_identifier_lookup_idx ON app.product_identifier (identifier_type, identifier_norm)`,
  `CREATE INDEX identifier_candidate_decision_created_idx ON app.identifier_candidate (decision_status, created_at)`,
  `CREATE INDEX import_batch_status_created_idx ON app.import_batch (status, created_at)`,
  `CREATE INDEX identifier_resolve_run_status_created_idx ON app.identifier_resolve_run (status, created_at)`,
  `CREATE INDEX thumbnail_job_status_created_idx ON app.thumbnail_job (status, created_at)`,
  `CREATE INDEX automation_run_status_created_idx ON app.automation_run (status, created_at)`,
  `CREATE FUNCTION app.validate_automation_timezone() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_timezone_names WHERE name = NEW.timezone) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'Invalid automation timezone';
  END IF;
  RETURN NEW;
END
$$`,
  `CREATE TRIGGER automation_job_timezone_check BEFORE INSERT OR UPDATE OF timezone ON app.automation_job FOR EACH ROW EXECUTE FUNCTION app.validate_automation_timezone()`,
  `INSERT INTO app.platform (code, name, platform_role) VALUES
  ('MUSINSA', 'MUSINSA', 'SOURCE'), ('OLIVEYOUNG', 'OLIVEYOUNG', 'SOURCE'),
  ('COUPANG', 'COUPANG', 'CHANNEL'), ('NAVER', 'NAVER', 'CHANNEL')`,
];
